#!/bin/bash
#
# Create .git/hooks/pre-push (e.g. from the example you find there) and add the line
#
# git-hooks/pre-push
#
# SPDX-FileCopyrightText: 2023 The WESkit Contributors
#
# SPDX-License-Identifier: MIT

set -ue

hooksDir="$(dirname "$BASH_SOURCE")"

# The pre-commit checks are fast and added again here, because if you do a rebase you may end up
# with failing code. So before you push, everything should be checked (again).

if [[ ! -v NO_PUSH_CHECKS || (-v NO_PUSH_CHECKS && "$NO_PUSH_CHECKS" != "true") ]]; then
  # Run the tests
  "$hooksDir/pre-commit"
  python -m pytest -v --cov=weskit/ -m "not slow"

fi