#!/bin/bash
#
# Create .git/hooks/pre-commit (e.g. from the example you find there) and add the line
#
# git-hooks/pre-commit
#

set -ue

if [[ ! -v NO_COMMIT_CHECKS || (-v NO_COMMIT_CHECKS && "$NO_COMMIT_CHECKS" != "true") ]]; then

  # Type checks
  echo "Mypy ..." >> /dev/stderr
  mypy tests/ weskit/ uwsgi_server/ tools/

  # Code style checks
  echo "flake8 ..." >> /dev/stderr
  flake8 tests/ weskit/ uwsgi_server/ tools/

  # Security
  echo "bandit ..." >> /dev/stderr
  bandit -r weskit/ uwsgi_server/

  # Run unit tests
  echo "pytest ..." >> /dev/stderr
  python -m pytest -m "not integration"

fi