# SPDX-FileCopyrightText: 2023 The WESkit Contributors
#
# SPDX-License-Identifier: MIT

FROM continuumio/miniconda3:23.5.2-0

LABEL maintainer="Philip R. Kensche <p.kensche@dkfz.de>"
LABEL org.opencontainers.image.source="https://registry.gitlab.com/one-touch-pipeline/weskit/api/base"

# Capitalized versions for many tools. Minuscle version at least for apt.
ARG HTTP_PROXY=""
ARG http_proxy="$HTTP_PROXY"
ARG HTTPS_PROXY=""
ARG https_proxy="$HTTPS_PROXY"
ARG NO_PROXY=""
ARG no_proxy="$NO_PROXY"

# Use (likely) unused user and group IDs by default.
ARG USER=weskit
ARG GROUP=weskit
ARG USER_ID="35671"
ARG GROUP_ID="35671"

RUN groupadd -r "$GROUP" -g "$GROUP_ID" && \
	useradd -r -s /bin/false -m -d /home/weskit -g "$GROUP" -u "$USER_ID" "$USER"

RUN mkdir /weskit \
    && chown -R "$USER:$GROUP" /weskit /opt/conda \
    && chmod -R 0770 /home/weskit /weskit /opt/conda \
    && umask 0770

RUN apt-get --allow-releaseinfo-change update && \
    apt-get install -y --no-install-recommends curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $USER:$GROUP

# Set up the Conda environment

# /home/weskit is used for the shell configuration (for Conda!) and the configuration files.
SHELL ["/bin/bash", "-c"]

# BASH_ENV needs to be set for the Conda setup.
ENV BASH_ENV /home/weskit/.bashrc

RUN conda init bash

RUN conda config --set proxy_servers.http "$HTTP_PROXY" && \
    conda config --set proxy_servers.https "$HTTPS_PROXY" && \
    conda config --set channel_priority strict && \
    echo "Installing mamba ..." && \
    conda install -n base -c conda-forge -c nodefaults mamba

# Note: With the Conda version 4.9.2, the environment.yaml must be located in a writable
# directory, or Conda will fail with a permission denied error.
COPY environment.yaml /weskit/environment.yaml
RUN echo "Creating environment ..." && \
    conda config --set channel_priority flexible && \
    mamba env create -n weskit -f /weskit/environment.yaml && \
    source activate weskit && \
    echo "Cleaning packages ..." && \
    conda clean --all -f -y && \
    echo "source activate nf-seq-convert" >> ~/.bashrc

# Ensures the following path will be a file, when mounted into the container (otherwise it will be a
# directory).
# TODO Remove after switching to helm. There it's /home/weskit/configs/config.yaml and works anyway.
RUN touch /home/weskit/config.yaml

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "weskit"]
