# SPDX-FileCopyrightText: 2023 The WESkit Contributors
#
# SPDX-License-Identifier: MIT

version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: "%(asctime)s %(levelname)s %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%SZ"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard
        stream: ext://sys.stderr
root:
    handlers: [console]
    level: DEBUG
asyncio:
    # See https://docs.python.org/3/library/asyncio-dev.html#debug-modeß
    level: DEBUG
    handlers: [console]
asyncssh:
    level: DEBUG
    handlers: [console]