# SPDX-FileCopyrightText: 2023 2023 The WESkit Team
#
# SPDX-License-Identifier: MIT

version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: "%(asctime)s %(levelname)s %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%SZ"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout
root:
    handlers: [console]
    level: INFO
